services:
  mysql:
    image: mysql:9.3
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urls
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
volumes:
  mysql-data:
