// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/common/base_entity.proto

package pagination

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectTypeID int32

const (
	ObjectTypeID_OBJECT_TYPE_UNSPECIFIED ObjectTypeID = 0
	ObjectTypeID_OBJECT_TYPE_SPORT       ObjectTypeID = 1
	ObjectTypeID_OBJECT_TYPE_REGION      ObjectTypeID = 2
	ObjectTypeID_OBJECT_TYPE_COMPETITION ObjectTypeID = 3
	ObjectTypeID_OBJECT_TYPE_MATCH       ObjectTypeID = 4
	ObjectTypeID_OBJECT_TYPE_MARKET_TYPE ObjectTypeID = 5
)

// Enum value maps for ObjectTypeID.
var (
	ObjectTypeID_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "OBJECT_TYPE_SPORT",
		2: "OBJECT_TYPE_REGION",
		3: "OBJECT_TYPE_COMPETITION",
		4: "OBJECT_TYPE_MATCH",
		5: "OBJECT_TYPE_MARKET_TYPE",
	}
	ObjectTypeID_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"OBJECT_TYPE_SPORT":       1,
		"OBJECT_TYPE_REGION":      2,
		"OBJECT_TYPE_COMPETITION": 3,
		"OBJECT_TYPE_MATCH":       4,
		"OBJECT_TYPE_MARKET_TYPE": 5,
	}
)

func (x ObjectTypeID) Enum() *ObjectTypeID {
	p := new(ObjectTypeID)
	*p = x
	return p
}

func (x ObjectTypeID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectTypeID) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[0].Descriptor()
}

func (ObjectTypeID) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[0]
}

func (x ObjectTypeID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectTypeID.Descriptor instead.
func (ObjectTypeID) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{0}
}

type MatchStatus int32

const (
	MatchStatus_NOT_STARTED     MatchStatus = 0
	MatchStatus_STARTED         MatchStatus = 1
	MatchStatus_COMPLETED_MATCH MatchStatus = 2
	MatchStatus_CANCELLED_MATCH MatchStatus = 3
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "NOT_STARTED",
		1: "STARTED",
		2: "COMPLETED_MATCH",
		3: "CANCELLED_MATCH",
	}
	MatchStatus_value = map[string]int32{
		"NOT_STARTED":     0,
		"STARTED":         1,
		"COMPLETED_MATCH": 2,
		"CANCELLED_MATCH": 3,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[1].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[1]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{1}
}

type LiveStatus int32

const (
	LiveStatus_NOT_AVAILABLE  LiveStatus = 0
	LiveStatus_AVAILABLE      LiveStatus = 1
	LiveStatus_COMPLETED_LIVE LiveStatus = 2
	LiveStatus_CANCELLED_LIVE LiveStatus = 3
)

// Enum value maps for LiveStatus.
var (
	LiveStatus_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "AVAILABLE",
		2: "COMPLETED_LIVE",
		3: "CANCELLED_LIVE",
	}
	LiveStatus_value = map[string]int32{
		"NOT_AVAILABLE":  0,
		"AVAILABLE":      1,
		"COMPLETED_LIVE": 2,
		"CANCELLED_LIVE": 3,
	}
)

func (x LiveStatus) Enum() *LiveStatus {
	p := new(LiveStatus)
	*p = x
	return p
}

func (x LiveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[2].Descriptor()
}

func (LiveStatus) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[2]
}

func (x LiveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveStatus.Descriptor instead.
func (LiveStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{2}
}

type SubscriptionType int32

const (
	SubscriptionType_SUBSCRIPTION_TYPE_LIVE     SubscriptionType = 0
	SubscriptionType_SUBSCRIPTION_TYPE_PREMATCH SubscriptionType = 1
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "SUBSCRIPTION_TYPE_LIVE",
		1: "SUBSCRIPTION_TYPE_PREMATCH",
	}
	SubscriptionType_value = map[string]int32{
		"SUBSCRIPTION_TYPE_LIVE":     0,
		"SUBSCRIPTION_TYPE_PREMATCH": 1,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[3].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[3]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{3}
}

type TypeFlag int32

const (
	TypeFlag_NOT_DEFINED       TypeFlag = 0
	TypeFlag_LIVE_AND_PREMATCH TypeFlag = 1
	TypeFlag_ONLY_PREMATCH     TypeFlag = 2
	TypeFlag_ONLY_LIVE         TypeFlag = 3
)

// Enum value maps for TypeFlag.
var (
	TypeFlag_name = map[int32]string{
		0: "NOT_DEFINED",
		1: "LIVE_AND_PREMATCH",
		2: "ONLY_PREMATCH",
		3: "ONLY_LIVE",
	}
	TypeFlag_value = map[string]int32{
		"NOT_DEFINED":       0,
		"LIVE_AND_PREMATCH": 1,
		"ONLY_PREMATCH":     2,
		"ONLY_LIVE":         3,
	}
)

func (x TypeFlag) Enum() *TypeFlag {
	p := new(TypeFlag)
	*p = x
	return p
}

func (x TypeFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[4].Descriptor()
}

func (TypeFlag) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[4]
}

func (x TypeFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeFlag.Descriptor instead.
func (TypeFlag) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{4}
}

type Outcome int32

const (
	Outcome_NOT_RESULTED   Outcome = 0
	Outcome_PLACE          Outcome = 1
	Outcome_RETURN_OUTCOME Outcome = 2
	Outcome_LOST           Outcome = 3
	Outcome_WON            Outcome = 4
	Outcome_WIN_RETURN     Outcome = 5
	Outcome_LOSE_RETURN    Outcome = 6
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "NOT_RESULTED",
		1: "PLACE",
		2: "RETURN_OUTCOME",
		3: "LOST",
		4: "WON",
		5: "WIN_RETURN",
		6: "LOSE_RETURN",
	}
	Outcome_value = map[string]int32{
		"NOT_RESULTED":   0,
		"PLACE":          1,
		"RETURN_OUTCOME": 2,
		"LOST":           3,
		"WON":            4,
		"WIN_RETURN":     5,
		"LOSE_RETURN":    6,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_base_entity_proto_enumTypes[5].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_api_common_base_entity_proto_enumTypes[5]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{5}
}

type ModifiedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedBy     string                 `protobuf:"bytes,1,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifiedEntity) Reset() {
	*x = ModifiedEntity{}
	mi := &file_api_common_base_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifiedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifiedEntity) ProtoMessage() {}

func (x *ModifiedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_base_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifiedEntity.ProtoReflect.Descriptor instead.
func (*ModifiedEntity) Descriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{0}
}

func (x *ModifiedEntity) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ModifiedEntity) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ModifiedEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModifiedEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SoftDeleteEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedBy     string                 `protobuf:"bytes,1,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeleteEntity) Reset() {
	*x = SoftDeleteEntity{}
	mi := &file_api_common_base_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeleteEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeleteEntity) ProtoMessage() {}

func (x *SoftDeleteEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_base_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeleteEntity.ProtoReflect.Descriptor instead.
func (*SoftDeleteEntity) Descriptor() ([]byte, []int) {
	return file_api_common_base_entity_proto_rawDescGZIP(), []int{1}
}

func (x *SoftDeleteEntity) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *SoftDeleteEntity) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_api_common_base_entity_proto protoreflect.FileDescriptor

const file_api_common_base_entity_proto_rawDesc = "" +
	"\n" +
	"\x1capi/common/base_entity.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x0eModifiedEntity\x12\x1c\n" +
	"\tcreatedBy\x18\x01 \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\x02 \x01(\tR\tupdatedBy\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"j\n" +
	"\x10SoftDeleteEntity\x12\x1c\n" +
	"\tdeletedBy\x18\x01 \x01(\tR\tdeletedBy\x128\n" +
	"\tdeletedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt*\xab\x01\n" +
	"\fObjectTypeID\x12\x1b\n" +
	"\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OBJECT_TYPE_SPORT\x10\x01\x12\x16\n" +
	"\x12OBJECT_TYPE_REGION\x10\x02\x12\x1b\n" +
	"\x17OBJECT_TYPE_COMPETITION\x10\x03\x12\x15\n" +
	"\x11OBJECT_TYPE_MATCH\x10\x04\x12\x1b\n" +
	"\x17OBJECT_TYPE_MARKET_TYPE\x10\x05*U\n" +
	"\vMatchStatus\x12\x0f\n" +
	"\vNOT_STARTED\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x01\x12\x13\n" +
	"\x0fCOMPLETED_MATCH\x10\x02\x12\x13\n" +
	"\x0fCANCELLED_MATCH\x10\x03*V\n" +
	"\n" +
	"LiveStatus\x12\x11\n" +
	"\rNOT_AVAILABLE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\x12\n" +
	"\x0eCOMPLETED_LIVE\x10\x02\x12\x12\n" +
	"\x0eCANCELLED_LIVE\x10\x03*N\n" +
	"\x10SubscriptionType\x12\x1a\n" +
	"\x16SUBSCRIPTION_TYPE_LIVE\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_TYPE_PREMATCH\x10\x01*T\n" +
	"\bTypeFlag\x12\x0f\n" +
	"\vNOT_DEFINED\x10\x00\x12\x15\n" +
	"\x11LIVE_AND_PREMATCH\x10\x01\x12\x11\n" +
	"\rONLY_PREMATCH\x10\x02\x12\r\n" +
	"\tONLY_LIVE\x10\x03*n\n" +
	"\aOutcome\x12\x10\n" +
	"\fNOT_RESULTED\x10\x00\x12\t\n" +
	"\x05PLACE\x10\x01\x12\x12\n" +
	"\x0eRETURN_OUTCOME\x10\x02\x12\b\n" +
	"\x04LOST\x10\x03\x12\a\n" +
	"\x03WON\x10\x04\x12\x0e\n" +
	"\n" +
	"WIN_RETURN\x10\x05\x12\x0f\n" +
	"\vLOSE_RETURN\x10\x06B@Z>gitlab.betmaker365.com/dev-viet/smm-document/api/common;commonb\x06proto3"

var (
	file_api_common_base_entity_proto_rawDescOnce sync.Once
	file_api_common_base_entity_proto_rawDescData []byte
)

func file_api_common_base_entity_proto_rawDescGZIP() []byte {
	file_api_common_base_entity_proto_rawDescOnce.Do(func() {
		file_api_common_base_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_base_entity_proto_rawDesc), len(file_api_common_base_entity_proto_rawDesc)))
	})
	return file_api_common_base_entity_proto_rawDescData
}

var (
	file_api_common_base_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
	file_api_common_base_entity_proto_msgTypes  = make([]protoimpl.MessageInfo, 2)
	file_api_common_base_entity_proto_goTypes   = []any{
		(ObjectTypeID)(0),             // 0: common.ObjectTypeID
		(MatchStatus)(0),              // 1: common.MatchStatus
		(LiveStatus)(0),               // 2: common.LiveStatus
		(SubscriptionType)(0),         // 3: common.SubscriptionType
		(TypeFlag)(0),                 // 4: common.TypeFlag
		(Outcome)(0),                  // 5: common.Outcome
		(*ModifiedEntity)(nil),        // 6: common.ModifiedEntity
		(*SoftDeleteEntity)(nil),      // 7: common.SoftDeleteEntity
		(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	}
)
var file_api_common_base_entity_proto_depIdxs = []int32{
	8, // 0: common.ModifiedEntity.createdAt:type_name -> google.protobuf.Timestamp
	8, // 1: common.ModifiedEntity.updatedAt:type_name -> google.protobuf.Timestamp
	8, // 2: common.SoftDeleteEntity.deletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_common_base_entity_proto_init() }
func file_api_common_base_entity_proto_init() {
	if File_api_common_base_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_base_entity_proto_rawDesc), len(file_api_common_base_entity_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_base_entity_proto_goTypes,
		DependencyIndexes: file_api_common_base_entity_proto_depIdxs,
		EnumInfos:         file_api_common_base_entity_proto_enumTypes,
		MessageInfos:      file_api_common_base_entity_proto_msgTypes,
	}.Build()
	File_api_common_base_entity_proto = out.File
	file_api_common_base_entity_proto_goTypes = nil
	file_api_common_base_entity_proto_depIdxs = nil
}
