// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common/base_entity.proto

package pagination

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ModifiedEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ModifiedEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModifiedEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ModifiedEntityMultiError,
// or nil if none found.
func (m *ModifiedEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *ModifiedEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CreatedBy

	// no validation rules for UpdatedBy

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModifiedEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModifiedEntityValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModifiedEntityValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModifiedEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModifiedEntityValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModifiedEntityValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModifiedEntityMultiError(errors)
	}

	return nil
}

// ModifiedEntityMultiError is an error wrapping multiple validation errors
// returned by ModifiedEntity.ValidateAll() if the designated constraints
// aren't met.
type ModifiedEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModifiedEntityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModifiedEntityMultiError) AllErrors() []error { return m }

// ModifiedEntityValidationError is the validation error returned by
// ModifiedEntity.Validate if the designated constraints aren't met.
type ModifiedEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModifiedEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModifiedEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModifiedEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModifiedEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModifiedEntityValidationError) ErrorName() string { return "ModifiedEntityValidationError" }

// Error satisfies the builtin error interface
func (e ModifiedEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModifiedEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModifiedEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModifiedEntityValidationError{}

// Validate checks the field values on SoftDeleteEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SoftDeleteEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SoftDeleteEntity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SoftDeleteEntityMultiError, or nil if none found.
func (m *SoftDeleteEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *SoftDeleteEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeletedBy

	if all {
		switch v := interface{}(m.GetDeletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SoftDeleteEntityValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SoftDeleteEntityValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SoftDeleteEntityValidationError{
				field:  "DeletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SoftDeleteEntityMultiError(errors)
	}

	return nil
}

// SoftDeleteEntityMultiError is an error wrapping multiple validation errors
// returned by SoftDeleteEntity.ValidateAll() if the designated constraints
// aren't met.
type SoftDeleteEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SoftDeleteEntityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SoftDeleteEntityMultiError) AllErrors() []error { return m }

// SoftDeleteEntityValidationError is the validation error returned by
// SoftDeleteEntity.Validate if the designated constraints aren't met.
type SoftDeleteEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SoftDeleteEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SoftDeleteEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SoftDeleteEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SoftDeleteEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SoftDeleteEntityValidationError) ErrorName() string { return "SoftDeleteEntityValidationError" }

// Error satisfies the builtin error interface
func (e SoftDeleteEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSoftDeleteEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SoftDeleteEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SoftDeleteEntityValidationError{}
