// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/common/pagination.proto

package pagination

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CODE int32

const (
	CODE_Success                   CODE = 0
	CODE_ParamInvalid              CODE = 2003
	CODE_TimeInvalid               CODE = 2004
	CODE_QueryNotFound             CODE = 2005
	CODE_UuidInvalid               CODE = 2006
	CODE_NotFound                  CODE = 2007
	CODE_DuplicateData             CODE = 2008
	CODE_ConflictData              CODE = 2009
	CODE_InvalidToken              CODE = 3001
	CODE_InvalidOTP                CODE = 3002
	CODE_AcceptDenied              CODE = 3003
	CODE_UsernameInvalid           CODE = 3004
	CODE_PasswordInvalid           CODE = 3005
	CODE_CantSendEmailOtp          CODE = 4003
	CODE_AuthFailed                CODE = 4005
	CODE_UserHasExists             CODE = 5001
	CODE_OtpNotExists              CODE = 6009
	CODE_UserOtpNotExists          CODE = 6008
	CODE_TwoFactorAuthSetupFailed  CODE = 8001
	CODE_TwoFactorAuthVerifyFailed CODE = 8002
	CODE_InternalServerErr         CODE = 9999
	CODE_DatabaseErr               CODE = 9998
	CODE_AccountSer                CODE = 1001
	CODE_BetDataSer                CODE = 1002
	CODE_SubscriptionSer           CODE = 1003
	CODE_NotificationSer           CODE = 1004
	CODE_OrchestrationSer          CODE = 1005
)

// Enum value maps for CODE.
var (
	CODE_name = map[int32]string{
		0:    "Success",
		2003: "ParamInvalid",
		2004: "TimeInvalid",
		2005: "QueryNotFound",
		2006: "UuidInvalid",
		2007: "NotFound",
		2008: "DuplicateData",
		2009: "ConflictData",
		3001: "InvalidToken",
		3002: "InvalidOTP",
		3003: "AcceptDenied",
		3004: "UsernameInvalid",
		3005: "PasswordInvalid",
		4003: "CantSendEmailOtp",
		4005: "AuthFailed",
		5001: "UserHasExists",
		6009: "OtpNotExists",
		6008: "UserOtpNotExists",
		8001: "TwoFactorAuthSetupFailed",
		8002: "TwoFactorAuthVerifyFailed",
		9999: "InternalServerErr",
		9998: "DatabaseErr",
		1001: "AccountSer",
		1002: "BetDataSer",
		1003: "SubscriptionSer",
		1004: "NotificationSer",
		1005: "OrchestrationSer",
	}
	CODE_value = map[string]int32{
		"Success":                   0,
		"ParamInvalid":              2003,
		"TimeInvalid":               2004,
		"QueryNotFound":             2005,
		"UuidInvalid":               2006,
		"NotFound":                  2007,
		"DuplicateData":             2008,
		"ConflictData":              2009,
		"InvalidToken":              3001,
		"InvalidOTP":                3002,
		"AcceptDenied":              3003,
		"UsernameInvalid":           3004,
		"PasswordInvalid":           3005,
		"CantSendEmailOtp":          4003,
		"AuthFailed":                4005,
		"UserHasExists":             5001,
		"OtpNotExists":              6009,
		"UserOtpNotExists":          6008,
		"TwoFactorAuthSetupFailed":  8001,
		"TwoFactorAuthVerifyFailed": 8002,
		"InternalServerErr":         9999,
		"DatabaseErr":               9998,
		"AccountSer":                1001,
		"BetDataSer":                1002,
		"SubscriptionSer":           1003,
		"NotificationSer":           1004,
		"OrchestrationSer":          1005,
	}
)

func (x CODE) Enum() *CODE {
	p := new(CODE)
	*p = x
	return p
}

func (x CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_pagination_proto_enumTypes[0].Descriptor()
}

func (CODE) Type() protoreflect.EnumType {
	return &file_api_common_pagination_proto_enumTypes[0]
}

func (x CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CODE.Descriptor instead.
func (CODE) EnumDescriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{0}
}

type OP int32

const (
	OP_OP_LT          OP = 0
	OP_OP_LTE         OP = 1
	OP_OP_GT          OP = 2
	OP_OP_GTE         OP = 3
	OP_OP_EQ          OP = 4
	OP_OP_NEQ         OP = 5
	OP_OP_LIKE        OP = 6
	OP_OP_IS_NULL     OP = 7
	OP_OP_IS_NOT_NULL OP = 8
	OP_OP_IN          OP = 9
	OP_OP_NOT_IN      OP = 10
)

// Enum value maps for OP.
var (
	OP_name = map[int32]string{
		0:  "OP_LT",
		1:  "OP_LTE",
		2:  "OP_GT",
		3:  "OP_GTE",
		4:  "OP_EQ",
		5:  "OP_NEQ",
		6:  "OP_LIKE",
		7:  "OP_IS_NULL",
		8:  "OP_IS_NOT_NULL",
		9:  "OP_IN",
		10: "OP_NOT_IN",
	}
	OP_value = map[string]int32{
		"OP_LT":          0,
		"OP_LTE":         1,
		"OP_GT":          2,
		"OP_GTE":         3,
		"OP_EQ":          4,
		"OP_NEQ":         5,
		"OP_LIKE":        6,
		"OP_IS_NULL":     7,
		"OP_IS_NOT_NULL": 8,
		"OP_IN":          9,
		"OP_NOT_IN":      10,
	}
)

func (x OP) Enum() *OP {
	p := new(OP)
	*p = x
	return p
}

func (x OP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OP) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_pagination_proto_enumTypes[1].Descriptor()
}

func (OP) Type() protoreflect.EnumType {
	return &file_api_common_pagination_proto_enumTypes[1]
}

func (x OP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OP.Descriptor instead.
func (OP) EnumDescriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{1}
}

type SortType int32

const (
	SortType_ASC  SortType = 0
	SortType_DESC SortType = 1
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortType_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_pagination_proto_enumTypes[2].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_api_common_pagination_proto_enumTypes[2]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{2}
}

type PaginationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     int32                  `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRes) Reset() {
	*x = PaginationRes{}
	mi := &file_api_common_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRes) ProtoMessage() {}

func (x *PaginationRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRes.ProtoReflect.Descriptor instead.
func (*PaginationRes) Descriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationRes) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *PaginationRes) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PaginationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageIndex     int32                  `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationReq) Reset() {
	*x = PaginationReq{}
	mi := &file_api_common_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationReq) ProtoMessage() {}

func (x *PaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationReq.ProtoReflect.Descriptor instead.
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *PaginationReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            OP                     `protobuf:"varint,3,opt,name=op,proto3,enum=common.OP" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_api_common_pagination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_pagination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Filter) GetOp() OP {
	if x != nil {
		return x.Op
	}
	return OP_OP_LT
}

type ErrMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrMsg) Reset() {
	*x = ErrMsg{}
	mi := &file_api_common_pagination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrMsg) ProtoMessage() {}

func (x *ErrMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_pagination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrMsg.ProtoReflect.Descriptor instead.
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{3}
}

func (x *ErrMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SortMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         SortType               `protobuf:"varint,2,opt,name=value,proto3,enum=common.SortType" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortMethod) Reset() {
	*x = SortMethod{}
	mi := &file_api_common_pagination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortMethod) ProtoMessage() {}

func (x *SortMethod) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_pagination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortMethod.ProtoReflect.Descriptor instead.
func (*SortMethod) Descriptor() ([]byte, []int) {
	return file_api_common_pagination_proto_rawDescGZIP(), []int{4}
}

func (x *SortMethod) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SortMethod) GetValue() SortType {
	if x != nil {
		return x.Value
	}
	return SortType_ASC
}

var File_api_common_pagination_proto protoreflect.FileDescriptor

const file_api_common_pagination_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/common/pagination.proto\x12\x06common\x1a\x17validate/validate.proto\"_\n" +
	"\rPaginationRes\x12\x1c\n" +
	"\tpageIndex\x18\x01 \x01(\x05R\tpageIndex\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"[\n" +
	"\rPaginationReq\x12%\n" +
	"\tpageIndex\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\tpageIndex\x12#\n" +
	"\bpageSize\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bpageSize\"L\n" +
	"\x06Filter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\x02op\x18\x03 \x01(\x0e2\n" +
	".common.OPR\x02op\"6\n" +
	"\x06ErrMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\n" +
	"SortMethod\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\x0e2\x10.common.SortTypeR\x05value*\xab\x04\n" +
	"\x04CODE\x12\v\n" +
	"\aSuccess\x10\x00\x12\x11\n" +
	"\fParamInvalid\x10\xd3\x0f\x12\x10\n" +
	"\vTimeInvalid\x10\xd4\x0f\x12\x12\n" +
	"\rQueryNotFound\x10\xd5\x0f\x12\x10\n" +
	"\vUuidInvalid\x10\xd6\x0f\x12\r\n" +
	"\bNotFound\x10\xd7\x0f\x12\x12\n" +
	"\rDuplicateData\x10\xd8\x0f\x12\x11\n" +
	"\fConflictData\x10\xd9\x0f\x12\x11\n" +
	"\fInvalidToken\x10\xb9\x17\x12\x0f\n" +
	"\n" +
	"InvalidOTP\x10\xba\x17\x12\x11\n" +
	"\fAcceptDenied\x10\xbb\x17\x12\x14\n" +
	"\x0fUsernameInvalid\x10\xbc\x17\x12\x14\n" +
	"\x0fPasswordInvalid\x10\xbd\x17\x12\x15\n" +
	"\x10CantSendEmailOtp\x10\xa3\x1f\x12\x0f\n" +
	"\n" +
	"AuthFailed\x10\xa5\x1f\x12\x12\n" +
	"\rUserHasExists\x10\x89'\x12\x11\n" +
	"\fOtpNotExists\x10\xf9.\x12\x15\n" +
	"\x10UserOtpNotExists\x10\xf8.\x12\x1d\n" +
	"\x18TwoFactorAuthSetupFailed\x10\xc1>\x12\x1e\n" +
	"\x19TwoFactorAuthVerifyFailed\x10\xc2>\x12\x16\n" +
	"\x11InternalServerErr\x10\x8fN\x12\x10\n" +
	"\vDatabaseErr\x10\x8eN\x12\x0f\n" +
	"\n" +
	"AccountSer\x10\xe9\a\x12\x0f\n" +
	"\n" +
	"BetDataSer\x10\xea\a\x12\x14\n" +
	"\x0fSubscriptionSer\x10\xeb\a\x12\x14\n" +
	"\x0fNotificationSer\x10\xec\a\x12\x15\n" +
	"\x10OrchestrationSer\x10\xed\a*\x94\x01\n" +
	"\x02OP\x12\t\n" +
	"\x05OP_LT\x10\x00\x12\n" +
	"\n" +
	"\x06OP_LTE\x10\x01\x12\t\n" +
	"\x05OP_GT\x10\x02\x12\n" +
	"\n" +
	"\x06OP_GTE\x10\x03\x12\t\n" +
	"\x05OP_EQ\x10\x04\x12\n" +
	"\n" +
	"\x06OP_NEQ\x10\x05\x12\v\n" +
	"\aOP_LIKE\x10\x06\x12\x0e\n" +
	"\n" +
	"OP_IS_NULL\x10\a\x12\x12\n" +
	"\x0eOP_IS_NOT_NULL\x10\b\x12\t\n" +
	"\x05OP_IN\x10\t\x12\r\n" +
	"\tOP_NOT_IN\x10\n" +
	"*\x1d\n" +
	"\bSortType\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01B@Z>gitlab.betmaker365.com/dev-viet/smm-document/api/common;commonb\x06proto3"

var (
	file_api_common_pagination_proto_rawDescOnce sync.Once
	file_api_common_pagination_proto_rawDescData []byte
)

func file_api_common_pagination_proto_rawDescGZIP() []byte {
	file_api_common_pagination_proto_rawDescOnce.Do(func() {
		file_api_common_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_pagination_proto_rawDesc), len(file_api_common_pagination_proto_rawDesc)))
	})
	return file_api_common_pagination_proto_rawDescData
}

var (
	file_api_common_pagination_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
	file_api_common_pagination_proto_msgTypes  = make([]protoimpl.MessageInfo, 5)
	file_api_common_pagination_proto_goTypes   = []any{
		(CODE)(0),             // 0: common.CODE
		(OP)(0),               // 1: common.OP
		(SortType)(0),         // 2: common.SortType
		(*PaginationRes)(nil), // 3: common.PaginationRes
		(*PaginationReq)(nil), // 4: common.PaginationReq
		(*Filter)(nil),        // 5: common.Filter
		(*ErrMsg)(nil),        // 6: common.ErrMsg
		(*SortMethod)(nil),    // 7: common.SortMethod
	}
)
var file_api_common_pagination_proto_depIdxs = []int32{
	1, // 0: common.Filter.op:type_name -> common.OP
	2, // 1: common.SortMethod.value:type_name -> common.SortType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_common_pagination_proto_init() }
func file_api_common_pagination_proto_init() {
	if File_api_common_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_pagination_proto_rawDesc), len(file_api_common_pagination_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_pagination_proto_goTypes,
		DependencyIndexes: file_api_common_pagination_proto_depIdxs,
		EnumInfos:         file_api_common_pagination_proto_enumTypes,
		MessageInfos:      file_api_common_pagination_proto_msgTypes,
	}.Build()
	File_api_common_pagination_proto = out.File
	file_api_common_pagination_proto_goTypes = nil
	file_api_common_pagination_proto_depIdxs = nil
}
