// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common/pagination.proto

package pagination

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PaginationRes with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaginationRes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaginationRes with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationResMultiError, or
// nil if none found.
func (m *PaginationRes) ValidateAll() error {
	return m.validate(true)
}

func (m *PaginationRes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageIndex

	// no validation rules for PageSize

	// no validation rules for Total

	if len(errors) > 0 {
		return PaginationResMultiError(errors)
	}

	return nil
}

// PaginationResMultiError is an error wrapping multiple validation errors
// returned by PaginationRes.ValidateAll() if the designated constraints
// aren't met.
type PaginationResMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationResMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationResMultiError) AllErrors() []error { return m }

// PaginationResValidationError is the validation error returned by
// PaginationRes.Validate if the designated constraints aren't met.
type PaginationResValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationResValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationResValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationResValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationResValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationResValidationError) ErrorName() string { return "PaginationResValidationError" }

// Error satisfies the builtin error interface
func (e PaginationResValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationRes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationResValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationResValidationError{}

// Validate checks the field values on PaginationReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaginationReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaginationReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationReqMultiError, or
// nil if none found.
func (m *PaginationReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PaginationReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPageIndex() < 0 {
		err := PaginationReqValidationError{
			field:  "PageIndex",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPageSize() <= 0 {
		err := PaginationReqValidationError{
			field:  "PageSize",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PaginationReqMultiError(errors)
	}

	return nil
}

// PaginationReqMultiError is an error wrapping multiple validation errors
// returned by PaginationReq.ValidateAll() if the designated constraints
// aren't met.
type PaginationReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationReqMultiError) AllErrors() []error { return m }

// PaginationReqValidationError is the validation error returned by
// PaginationReq.Validate if the designated constraints aren't met.
type PaginationReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationReqValidationError) ErrorName() string { return "PaginationReqValidationError" }

// Error satisfies the builtin error interface
func (e PaginationReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationReqValidationError{}

// Validate checks the field values on Filter with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Filter with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FilterMultiError, or nil if none found.
func (m *Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	// no validation rules for Op

	if len(errors) > 0 {
		return FilterMultiError(errors)
	}

	return nil
}

// FilterMultiError is an error wrapping multiple validation errors returned by
// Filter.ValidateAll() if the designated constraints aren't met.
type FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FilterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FilterMultiError) AllErrors() []error { return m }

// FilterValidationError is the validation error returned by Filter.Validate if
// the designated constraints aren't met.
type FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilterValidationError) ErrorName() string { return "FilterValidationError" }

// Error satisfies the builtin error interface
func (e FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilterValidationError{}

// Validate checks the field values on ErrMsg with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrMsg) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrMsg with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ErrMsgMultiError, or nil if none found.
func (m *ErrMsg) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrMsg) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Message

	if len(errors) > 0 {
		return ErrMsgMultiError(errors)
	}

	return nil
}

// ErrMsgMultiError is an error wrapping multiple validation errors returned by
// ErrMsg.ValidateAll() if the designated constraints aren't met.
type ErrMsgMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrMsgMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrMsgMultiError) AllErrors() []error { return m }

// ErrMsgValidationError is the validation error returned by ErrMsg.Validate if
// the designated constraints aren't met.
type ErrMsgValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrMsgValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrMsgValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrMsgValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrMsgValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrMsgValidationError) ErrorName() string { return "ErrMsgValidationError" }

// Error satisfies the builtin error interface
func (e ErrMsgValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrMsg.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrMsgValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrMsgValidationError{}

// Validate checks the field values on SortMethod with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SortMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SortMethod with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SortMethodMultiError, or
// nil if none found.
func (m *SortMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *SortMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKey()) < 1 {
		err := SortMethodValidationError{
			field:  "Key",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Value

	if len(errors) > 0 {
		return SortMethodMultiError(errors)
	}

	return nil
}

// SortMethodMultiError is an error wrapping multiple validation errors
// returned by SortMethod.ValidateAll() if the designated constraints aren't met.
type SortMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SortMethodMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SortMethodMultiError) AllErrors() []error { return m }

// SortMethodValidationError is the validation error returned by
// SortMethod.Validate if the designated constraints aren't met.
type SortMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SortMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SortMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SortMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SortMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SortMethodValidationError) ErrorName() string { return "SortMethodValidationError" }

// Error satisfies the builtin error interface
func (e SortMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSortMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SortMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SortMethodValidationError{}
