ALLOW_ORIGINS: "*"

SERVER:
  PORT: 8081
  MODE: DEV
  LEVEL: INFO
  SERVICE_NAME: user
  ENVIRONMENT: local
  VERSION: 1.0

LOGGER:
  LOG_LEVEL: debug
  LOG_MAX_SIZE: 10
  LOG_MAX_AGE: 30
  LOG_MAX_BACKUPS: 5
  LOG_COMPRESS: true

SQL:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_DBNAME: urls
  RDBMS: mysql
  MAX_CONN_IDLE_TIME: 5
  MAX_CONN_LIFE_TIME: 5
  MAX_CONNS: 10
  MAX_IDLE_CONNS: 2

